### ISSUE TITLE
Create/remove player

### ISSUE THREAD

**Issue by bergacat1** [UdL-EPS-SoftArch/mypadel-api#4]
In order to allow a new player to use the app
As an admin
I want to create a new player account

**Comment by deinok** [comment]
@jordi002 @joanpaucg 
Nois, per fer la nostra part, necessitem la vostra. Si necessiteu ajuda estarem encantats de ajudar-vos ;)

**Comment by rogargon** [comment]
You can continue the development of "Add match result" while this feature is completed. For the moment, Match Result might ignore the field connecting it to Player or make it a String. Concentrate now on creating the repository for Match Result and the Cucumber tests. Later, we will add relationships to other model entities

**Comment by deinok** [comment]
@rogargon Okey, thanks @mrg20 and @ollara1

**Comment by joanpaucg** [comment]
Hi @deinok @rogargon  we have done the cucumber tests for Create/remove Player in the branch create/remove Player and they all pass, we haven't done a pull request yet.
